### ISSUE TITLE
Keisei breaks Tampermonkey Scripts

### ISSUE THREAD

**Issue by Koolstr** [mwil/wanikani-userscripts#1]
In the past few days, none of my Tampermonkey userscripts were working on WaniKani, even though the extension and all the scripts were enabled. After debugging, I found the culprit to be the Keisei script. When that script alone is disabled, the rest of my userscripts work again as normal.

Please look into this; something must have changed recently, probably in the way WaniKani's site or Tampermonkey's extension works.

**Comment by mwil** [comment]
I haven't noticed an issue yet, and there are no other reports of this issue. What OS, browser, Tampermonkey version are you using? Tampermonkey 4.7 for Chrome was released not too long ago.

When you have several script activated with Keisei, does Keisei work while nothing else works, or nothing at all works? What order of scripts are you using? And which other scripts fail?

There was an issue with another script of mine (Niai) because of some weird interaction of a Tampermonkey feature, but that was fixed (https://community.wanikani.com/t/userscript-wip-lock-script/24510/4).

I don't know what breaks for you, but I suspect that it is somehow related to Tampermonkey is acting strangely.

**Comment by Koolstr** [comment]
This is on Firefox, with Tampermonkey v4.8.5847. I've just tried enqueuing Keisei to run first out of all userscripts, but the problem persists. The problem remains even if it is the only script enabled.

This problem arose seemingly around the same time I updated to the latest version of Firefox. Perhaps look into that?

**Comment by mwil** [comment]
I tested on OSX and Windows on Firefox 62.0.2, Tampermonkey v4.8.5847, it is still working for me.

Is there any console output when you just use Keisei (Ctrl-Shift-K or Cmd-Opt-K)? Also, you can try to set Tampermonkey's *Logging Level* in Tampermonkey's **Settings > General** to *Debug*, it gives hopefully more hints what is causing this.

Are you using some specific security solution that might block Tampermonkey? Keisei uses advanced Tampermonkey features like reading styles from resource files that maybe no other userscript is using, and this might trigger a blocking reaction of the whole Tampermonkey.

**Comment by mwil** [comment]
I haven't found the source for this yet, but it must be within the recent changes.

For now you can downgrade to v1.6.7, this fixed the problem for other FF users. [Downgrade link](https://github.com/mwil/wanikani-userscripts/raw/f63c616afb74b84c8ec56195252eba6e1037dd98/wanikani-phonetic-compounds/wk_keisei.user.js)

**Comment by mwil** [comment]
I think I found the source for this problem, GM_getValue() completely trips Firefox when used with the optional default value.

Version 1.7.3 should fix your issue.

Please feel free to open another issue if this issue still persists for you.

**Comment by Koolstr** [comment]
Indeed, that seemed to be the issue. It works now. Thank you so much for being on top of this and fixing it!

**Comment by Koolstr** [comment]
The same problem now occurs for the Niai script as well. Please patch it there too.

**Comment by mwil** [comment]
Interesting, I didn't use the feature that broke Keisei there. I will check it out.

I added support for the Wanikani Open Framework to show which items are really unlocked, but it should be fully optional. To find where the problem is, do you have WKOF installed?
